### ISSUE TITLE
Pruebas Funcionales Básicas

### ISSUE THREAD

**Issue by cmonsalvec** [DeadlyBunny24/ExGarciaSum#1]
Estimado Juan José,

Favor asegurarse que las siguientes pruebas funcionan:

Nota: podría ser que la versión de Junit no sea la que está usando, ni los nombres de las clases probadas sean las mismas, entonces primero adaptar las pruebas según su trabajo.

Si termina esto, entonces espero me permita ver por este medio los resultados de las pruebas (captura), y el código correspondiente a las pruebas.

@Test
public void cuandoUnSoloNumeroEsUsadoSeRetornaEseValor() {
Assert.assertEquals(3, Sumador("3"));
}

@Test
public void cuandoDosNumerosSonUsadosEntoncesRetornamosSuSuma() {
Assert.assertEquals(9, Sumador("3,6"));
}

**Comment by DeadlyBunny24** [comment]
Error:
![issue_1_error](https://cloud.githubusercontent.com/assets/6155045/22701672/4ec1f9a8-ed2c-11e6-9b5b-c092c62173f9.PNG)

**Comment by DeadlyBunny24** [comment]
Solución:
![issue_1_resuelto](https://cloud.githubusercontent.com/assets/6155045/22701927/134e1c70-ed2d-11e6-8a85-e523e95a530d.PNG)
