### ISSUE TITLE
Deseo Sumar Mas de Dos Numeros

### ISSUE THREAD

**Issue by cmonsalvec** [DeadlyBunny24/ExGarciaSum#2]
Estimado Juan José,

Deseo que Sumadora pueda sumar más de dos números. Por ejemplo, debería poderse generar una prueba basado en el siguiente Assert:

Assert.assertEquals(3+6+15+18+46+33, Sumadora("3,6,15,18,46,33"));

Nuevamente, puede ser que se deba adaptar el Assert para el proyecto. Igual que antes notificarme por este medio el resultado de la prueba exitosa, y realizar el commit respectivo.

Gracias

**Comment by DeadlyBunny24** [comment]
Error: 
![issue_2_error](https://cloud.githubusercontent.com/assets/6155045/22702138/b1799e74-ed2d-11e6-83d4-49a51824b45c.PNG)

**Comment by DeadlyBunny24** [comment]
Solución:
![issue_2_resuelto](https://cloud.githubusercontent.com/assets/6155045/22702210/ecf838d4-ed2d-11e6-98c9-72e5d1524de4.PNG)
