### ISSUE TITLE
Eliminar números mágicos

### ISSUE THREAD

**Issue by cmonsalvec** [DeadlyBunny24/ExGarciaSum#4]
Estimado Juan José,

Veo que tiene algunos números mágicos en su código. Favor editar su código para eliminarlos de tal manera que su checkstyle ya no los marque.

Enviarme su checkstyle una vez corregido este problema.

**Comment by DeadlyBunny24** [comment]
[reporte.txt](https://github.com/DeadlyBunny24/ExGarciaSum/files/758561/reporte.txt)
